### Create a new user
POST http://localhost:3000/api/v1/user
content-type: application/json

{
    "firstName": "Linda",
    "lastName": "Muakliner",
    "email": "luis@gosleep.com",
    "password": "password"
}

### Authenticate
POST http://localhost:3000/api/auth
content-type: application/json

{
    "email": "james@foo.com",
    "password": "verystrongpassword"
}

### List all users
GET http://localhost:3000/api/v1/user
x-api-token: dadasdasdasdasdas

### Get single user
GET http://localhost:3000/api/v1/user/651ea7e462549ed7bda18fee

### Delete user
DELETE http://localhost:3000/api/v1/user/651e95ae8e7ad559a2375733

### Update user
PUT http://localhost:3000/api/v1/user/651ea7e462549ed7bda18fee
content-type: application/json

{
    "email": "jdnsad@dsa.com"
}

### Get hotels
GET http://localhost:3000/api/v1/hotel
x-api-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbWVzQGZvby5jb20iLCJleHBpcmVzIjoxNjk3MTA4ODIyLCJpZCI6IjY1MjRmNDI1NDIzZjAwY2E5YTM5OTJiOSJ9.ZlHKMrAJ0sB3Z2WVjAl-AKOBaUZqhWw0JRn_iX6AfnI

### Get rooms
GET http://localhost:3000/api/v1/hotel/65246500e1de659cfd752bb8

