### Create a new user
POST http://localhost:3000/api/v1/user
content-type: application/json

{
    "firstName": "Linda",
    "lastName": "Muakliner",
    "email": "luis@gosleep.com",
    "password": "password"
}

### Authenticate
POST http://localhost:3000/api/auth
content-type: application/json

{
    "email": "james@foo.com",
    "password": "verystrongpassword"
}

### List all users
GET http://localhost:3000/api/v1/user
x-api-token: dadasdasdasdasdas

### Get single user
GET http://localhost:3000/api/v1/user/651ea7e462549ed7bda18fee

### Delete user
DELETE http://localhost:3000/api/v1/user/651e95ae8e7ad559a2375733

### Update user
PUT http://localhost:3000/api/v1/user/651ea7e462549ed7bda18fee
content-type: application/json

{
    "email": "jdnsad@dsa.com"
}

### Get hotels
GET http://localhost:3000/api/v1/hotel
x-api-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbWVzQGZvby5jb20iLCJleHBpcmVzIjoxNjk3NjIyMDI3LCJpZCI6IjY1MmY2ZmNiMzRhYmU2NzMwNzAxMDc2ZSJ9.w0FAWUxM3t6FDblqitTNAjano7T0LO8nPx3_n714TMQ

### Get rooms
GET http://localhost:3000/api/v1/hotel/65246500e1de659cfd752bb8

### Get rooms for hotel
GET http://localhost:3000/api/v1/hotel/652ce25b8eced11cad2edc21/rooms
x-api-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbWVzQGZvby5jb20iLCJleHBpcmVzIjoxNjk3NTgzNzUxLCJpZCI6IjY1MmVkODM1YjdkMmNhOWI5YjQ2ZmE1NCJ9.hz2GGBoaXf4E8ErNUqeTtOSUbBpoiL2tk7uZqcFnDBI

### Post room id to book
POST http://localhost:3000/api/v1/room/652f6fcb34abe67307010763/book
x-api-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbWVzQGZvby5jb20iLCJleHBpcmVzIjoxNjk3NjIyMDI3LCJpZCI6IjY1MmY2ZmNiMzRhYmU2NzMwNzAxMDc2ZSJ9.w0FAWUxM3t6FDblqitTNAjano7T0LO8nPx3_n714TMQ
content-type: application/json

{
    "numPersons": 2,
    "fromDate": "2023-10-19T00:00:00Z",
    "tillDate": "2023-11-25T00:00:00Z"
}

### Get all rooms
GET http://localhost:3000/api/v1/room
x-api-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbWVzQGZvby5jb20iLCJleHBpcmVzIjoxNjk3NTg3OTM4LCJpZCI6IjY1MmVlYWEyYjFlMjBkZjljNjA4MzU2NiJ9.nSyjQDITHWoJ7x6Cu5_yDWGTZLps80vqMnABXunl7Fs

### Get bookings
GET http://localhost:3000/api/v1/admin/booking
x-api-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImV4cGlyZXMiOjE2OTc2MjM3MzMsImlkIjoiNjUyZjc2NzUzMTZiZjdiOWQ2NTJhMGMzIn0.uIIIcwji9BLmrD31o3TA3iK1f3YvAYYAyZs1cOcoO1Y
### Get booking
GET http://localhost:3000/api/v1/booking/652f70344da437cadcee36fc
x-api-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbWVzQGZvby5jb20iLCJleHBpcmVzIjoxNjk3NjIyMDI3LCJpZCI6IjY1MmY2ZmNiMzRhYmU2NzMwNzAxMDc2ZSJ9.w0FAWUxM3t6FDblqitTNAjano7T0LO8nPx3_n714TMQ

### Get booking CANCEL
GET http://localhost:3000/api/v1/booking/652f70344da437cadcee36fc/cancel
x-api-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbWVzQGZvby5jb20iLCJleHBpcmVzIjoxNjk3NjIyMDI3LCJpZCI6IjY1MmY2ZmNiMzRhYmU2NzMwNzAxMDc2ZSJ9.w0FAWUxM3t6FDblqitTNAjano7T0LO8nPx3_n714TMQ